name: loading_value
description: A declarative implementation of a loading value
version: 0.0.1
repository: https://github.com/timcreatedit/loading_value

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0